In [1]:
import pandas as pd
from unicodedata import numeric

In [3]:
df_ratings = pd.read_csv("IMDb ratings.csv")

In [10]:
df_movies = pd.read_csv("IMDb movies.csv", low_memory=False)

In [11]:
df_movies = df_movies[['imdb_title_id', 'title', 'year',
                       'genre', 'country', 'director', 'actors']]

In [13]:
df_ratings = df_ratings[['imdb_title_id', 'total_votes', 'mean_vote']]

# concat()

## Concatenate vertically

To concatenate vertically (along the rows) we should have columns in common between the 2 dataframes

In [21]:
df1 = pd.DataFrame({'id' : ['a', 'b', 'c', 'd'] , 'age' : [30 ,23 ,25, 36]})

In [19]:
df2 = pd.DataFrame({'id' : ['e', 'f', 'g', 'h'] , 'age' : [31 ,22 ,21, 32]})

In [23]:
df3 = pd.concat([df1, df2], ignore_index=True)

### Exercise

In [26]:
# extract a 50% sample of the original dataframe
df_movies1 = df_movies.sample(frac=0.5)

In [29]:
df_movies1.shape

(42928, 7)

In [30]:
df_movies.shape

(85855, 7)

In [35]:
# shape of dataframes that we'll concatenate
df_vertical = pd.concat([df_movies, df_movies1], ignore_index=True)
df_vertical.shape

(128783, 7)

## Concatenate horizontally

To concatenate horizontally (along the columns) we should have a common index between the 2 dataframes

In [37]:
df1 = pd.DataFrame({'id': ['A', 'B', 'C', 'D'],
                    'age': [30, 23, 25, 22]})
df2 = pd.DataFrame({'job': ['Doctor', 'Statistician',
                            'Accountant', 'Developer']})

In [38]:
pd.concat([df1, df2], ignore_index=True, axis=1)

   0   1             2
0  A  30        Doctor
1  B  23  Statistician
2  C  25    Accountant
3  D  22     Developer

### Exercise

In [54]:
# shape of dataframes that we'll concatenate
df1 = df_movies.set_index('imdb_title_id')

In [55]:
df2 = df_ratings.set_index('imdb_title_id')

In [56]:
# concatenate df_movies and df_ratings on 'imdb_title_id' (horizontally along the columns)
pd.concat([df1, df2], axis=1)

,title,year,genre,country,director,actors,total_votes,mean_vote
imdb_title_id,,,,,,,,
tt0000009,Miss Jerry,1894,Romance,USA,Alexander Black,"Blanche Bayliss, William Courtenay, Chauncey D...",154,5.9
tt0000574,The Story of the Kelly Gang,1906,"Biography, Crime, Drama",Australia,Charles Tait,"Elizabeth Tait, John Tait, Norman Campbell, Be...",589,6.3
tt0001892,Den sorte drøm,1911,Drama,"Germany, Denmark",Urban Gad,"Asta Nielsen, Valdemar Psilander, Gunnar Helse...",188,6.0
tt0002101,Cleopatra,1912,"Drama, History",USA,Charles L. Gaskill,"Helen Gardner, Pearl Sindelar, Miss Fielding, ...",446,5.3
tt0002130,L'Inferno,1911,"Adventure, Drama, Fantasy",Italy,"Francesco Bertolini, Adolfo Padovan","Salvatore Papa, Arturo Pirovano, Giuseppe de L...",2237,6.9
...,...,...,...,...,...,...,...,...
tt9908390,Le lion,2020,Comedy,"France, Belgium",Ludovic Colbeau-Justin,"Dany Boon, Philippe Katerine, Anne Serra, Samu...",398,5.5
tt9911196,De Beentjes van Sint-Hildegard,2020,"Comedy, Drama",Netherlands,Johan Nijenhuis,"Herman Finkers, Johanna ter Steege, Leonie ter...",724,7.9
tt9911774,Padmavyuhathile Abhimanyu,2019,Drama,India,Vineesh Aaradya,"Anoop Chandran, Indrans, Sona Nair, Simon Brit...",265,7.8
tt9914286,Sokagin Çocuklari,2019,"Drama, Family",Turkey,Ahmet Faik Akinci,"Ahmet Faik Akinci, Belma Mamati, Metin Keçeci,...",194,9.4
tt9914942,La vida sense la Sara Amat,2019,Drama,Spain,Laura Jou,"Maria Morera Colomer, Biel Rossell Pelfort, Is...",102,6.8

In [57]:
df1.shape

(85855, 6)

In [58]:
df2.shape

(85855, 2)